# 服务器端配置
SERVER_PORT = 8088
SERVER_IP = "127.0.0.1"
SERVER_FILE_FOLDER_PATH = "resources"

# 客户端socket配置
CLIENT_PORT = 12345
CLIENT_IP = "127.0.0.1"

# 客户端数据相关配置
DATA_SAVED_PATH = "data"
DATA_DECODE_EXE_PATH = "TAppDecoder.exe"
DATA_YUV_PATH = "yuv"
DATA_FRAME_PER_YUV = 50
DATA_HEIGHT = 480
DATA_WIDTH = 832

# 视频播放相关配置
VIDEO_IMAGE_PER_SECOND = 0.05
